Implement statx
managarm/mlibc pull request #1030
Opened 2024-03-05 21:25 UTC by FedorLap2006

Implement `statx` function and `sys_statx` sysdep for Linux.

2024-03-05 22:47 UTC, no92 requested changes
Small mistakes, other than that LGTM.

2024-03-05 22:47 UTC, no92 commented on abis/linux/statx.h
> +struct statx {
Given that linux documents that the size of this struct is `0x100`, we should static_assert on it.

2024-03-05 22:47 UTC, no92 commented on abis/linux/statx.h
> +	struct statx_timestamp stx_atim;
You are missing `stx_btime`.

2024-03-05 22:48 UTC, no92 commented
You should also reword the commit messages to align with the patches' contents and make sure that the commits are atomic.

2024-03-05 23:21 UTC, qookei approved these changes

2024-03-07 10:15 UTC, Geertiebear approved these changes

2024-03-07 10:15 UTC, merged