sysdeps/astral: upstream port
managarm/mlibc pull request #1136
Opened 2024-10-03 02:11 UTC by Mathewnd

2024-10-03 10:19 UTC, no92 reviewed
LGTM, all I can complain about is the two places that indent using 4 spaces instead of tabs.

2024-10-03 10:19 UTC, no92 commented on meson.build
> +        disable_crypt_option = true
You seem to have mixed indentation here.

2024-10-03 10:19 UTC, no92 commented on sysdeps/astral/crt-x86_64/crt0.S
> +    mov $main, %rdi
Indentation uses spaces instead of tabs here.

2024-10-03 11:53 UTC, mintsuki commented on meson.build
> +        disable_intl_option = true
I would leave these settings up to the configurer of mlibc rather than hardcoding them here. It also would align with the other ports.

2024-10-03 13:15 UTC, Geertiebear requested changes
Welcome to the mlibc family :)

2024-10-04 00:36 UTC, mintsuki approved these changes

2024-10-04 00:37 UTC, merged