A couple changes to increase compatability
managarm/mlibc pull request #354
Opened 2022-01-09 00:07 UTC by YusufKhan-gamedev

This adds a couple things to increase compatibility a bit on sbase.

2022-06-06 11:04 UTC, Geertiebear approved these changes
LGTM.

2022-06-06 12:06 UTC, ArsenArsen commented
why are those levels macros and where did this code come from?

2022-06-14 15:20 UTC, YusufKhan-gamedev commented
Everything was copied from musl

2022-06-14 16:08 UTC, no92 requested changes
The commit messages are not in the [style they should be](https://docs.managarm.org/handbook/contributing/commit-messages.html).

2022-06-14 16:08 UTC, no92 commented on options/posix/include/syslog.h
> +#define prioritynames ((CODE *)(const CODE []){ \
If these come from musl, putting at least a notice might be necessary, even though this is a header.

2022-06-14 18:19 UTC, ArsenArsen requested changes
and, again, the commits should be reworded (they seem to be separated well enough though)

2022-06-14 18:19 UTC, ArsenArsen commented on options/posix/include/syslog.h
> +	{ "local6", LOG_LOCAL6 }, { "local7", LOG_LOCAL7 }, { 0, -1 } })
why are these not an inline function?

2022-07-10 17:43 UTC, Geertiebear commented
Closing due to inactivity. Feel free to reopen if these changes are still necessary and our comments have been considered.

2022-07-10 17:43 UTC, closed without merging