Linux fixes for ncurses & readline.
managarm/mlibc pull request #396
Opened 2022-02-21 23:50 UTC by qookei

2022-02-22 12:53 UTC, no92 approved these changes

2022-04-08 18:44 UTC, Dennisbonke commented
LGTM

2022-04-08 18:44 UTC, Dennisbonke approved these changes

2022-04-09 06:49 UTC, avdgrinten commented on sysdeps/linux/generic/sysdeps.cpp
> +	}
`default: return EINVAL;`? What do other libcs do here?

2022-04-09 17:55 UTC, czapek1337 requested changes

2022-04-09 17:55 UTC, czapek1337 commented on sysdeps/linux/generic/sysdeps.cpp
> +	auto ret = do_syscall(NR_ioctl, TCGETS, attr);
The `fd` is missing from the syscall arguments

2022-04-09 17:55 UTC, czapek1337 commented on sysdeps/linux/generic/sysdeps.cpp
> +	auto ret = do_syscall(NR_ioctl, req, attr);
Same here as well

2022-04-09 18:13 UTC, czapek1337 requested changes

2022-04-09 18:13 UTC, czapek1337 commented on sysdeps/linux/generic/sysdeps.cpp
> +int sys_tcgetattr(int fd, struct termios *attr) {
Also the `sys_tcgetattr` signature expects the `attr` pointer to be const

2022-05-07 23:53 UTC, merged