Various additions to compile NSPR and NSS
managarm/mlibc pull request #415
Opened 2022-04-27 16:06 UTC by Dennisbonke

This PR adds some defines and structs to please `NSPR` and `NSS`.

2022-05-03 19:23 UTC, Geertiebear requested changes

2022-05-03 19:23 UTC, Geertiebear commented on options/bsd/include/sys/queue.h
> +} while (/*CONSTCOND*/0)
Remove these ``CONSTCOND`` comments.

2022-05-04 06:56 UTC, avdgrinten commented
The queue implementation seems to be taken from somewhere else. Remember to add licenses!

2022-05-06 23:43 UTC, Dennisbonke commented on options/bsd/include/sys/queue.h
> +} while (/*CONSTCOND*/0)
Done as requested.

2022-05-06 23:44 UTC, Dennisbonke commented
> The queue implementation seems to be taken from somewhere else. Remember to add licenses!

The header was taken from glibc, but the copyright header in it seems to be a BSD-3-Clause style header, so I think we're good, but I could be wrong.

2022-05-10 08:41 UTC, Geertiebear approved these changes
LGTM now.

2022-05-14 20:19 UTC, merged