options/posix: stub accept4
managarm/mlibc pull request #427
Opened 2022-05-15 12:25 UTC by no92

2022-05-15 13:21 UTC, Geertiebear requested changes
Please add a test.

2022-05-15 16:04 UTC, no92 commented
Rebased, added linux sysdeps and added a test.

2022-05-15 17:01 UTC, Geertiebear requested changes

2022-05-15 17:01 UTC, Geertiebear commented on options/posix/include/mlibc/posix-sysdeps.hpp
> +[[gnu::weak]] int sys_accept(int fd, int *newfd, struct sockaddr *addr_ptr, socklen_t *addr_length);
Could you please fix all sysdeps where ``sys_accept`` is implemented?

2022-05-16 07:49 UTC, Geertiebear approved these changes
LGTM.

2022-05-16 07:50 UTC, merged