abis: place {F,W,R,X}_OK in abi-bits
managarm/mlibc pull request #443
Opened 2022-06-02 02:19 UTC by 64

Fixes the ABI for `access` on Linux. Also adds an `access` test (and one for `longjmp` too, because why not)

2022-06-02 11:14 UTC, no92 approved these changes

2022-06-03 08:28 UTC, ArsenArsen commented
lgtm, but squash the last into the first commit

2022-06-03 22:19 UTC, Dennisbonke commented on sysdeps/managarm/meson.build
> +		'include/abi-bits/unistd.h',
This is wrong, please change this to be `access.h`.

2022-06-03 22:20 UTC, Dennisbonke requested changes
Breaks the Managarm build, please fix.

2022-06-06 11:03 UTC, Geertiebear approved these changes
LGTM.

2022-06-06 11:03 UTC, merged