sysdeps/linux: implement a few more sysdeps
managarm/mlibc pull request #497
Opened 2022-06-17 02:53 UTC by 64

This PR is part of the mlibc on Linux project.

(Dennis forced me to write that)

2022-06-17 02:59 UTC, Dennisbonke commented
> This PR is part of the mlibc on Linux project.
> 
> (Dennis forced me to write that)

I sure didn't, but it's true :^)

2022-06-20 11:38 UTC, Geertiebear requested changes
LGTM except for one comment.

2022-06-20 11:38 UTC, Geertiebear commented on options/glibc/generic/glibc-signal.cpp
> +#include <mlibc/posix-sysdeps.hpp>
We have a ``glibc-sysdeps.hpp``

2022-06-22 10:00 UTC, ArsenArsen commented on sysdeps/linux/generic/sysdeps.cpp
> +	return 0;
We can just call sys_dup (or NR_dup3) here

2022-06-26 12:51 UTC, Geertiebear approved these changes
LGTM.

2022-06-26 21:25 UTC, merged