Various additions for mlibc on Linux project
managarm/mlibc pull request #502
Opened 2022-06-17 03:26 UTC by 64

This PR is part of the mlibc on Linux project.

2022-06-17 03:29 UTC, 64 commented
The `ELF_ST_*` changes are ABI breaks.

2022-06-19 19:16 UTC, ArsenArsen requested changes
lgtm past this and perhaps elaborating on reasons (and shortening the message) on 84caae12c8952b82e341d376a11cdce471e9026b

2022-06-19 19:16 UTC, ArsenArsen commented on abis/linux/in.h
> +extern const struct in6_addr in6addr_any;
where's the definition?

2022-06-19 20:03 UTC, qookei approved these changes
LGTM

2022-06-19 20:03 UTC, ArsenArsen approved these changes

2022-06-19 20:04 UTC, Dennisbonke approved these changes
LGTM

2022-06-19 20:13 UTC, merged