meson: allow static and shared libs to be built simultaneously
managarm/mlibc pull request #515
Opened 2022-06-19 18:29 UTC by 64

Fixes #514.

Tests for now only build against the shared libraries when `default_library=both`, but this could probably be fixed in a future PR (maybe once the big refactor of `tests/meson.build` in #460 is merged).

It does make the main meson.build slightly messier, but it's probably worthwhile (and I don't see an obvious way to rewrite it more cleanly).

2022-06-20 08:56 UTC, ArsenArsen requested changes
Overall, this is pretty good, maybe factor out the common variables (list of sources namely)  between the if static and if shared block?

And a style nit

EDIT: might also be worth adding a dynamic-only test

2022-06-20 08:56 UTC, ArsenArsen commented on meson.build
> +	if library_type == 'shared' or library_type == 'both'
`library_type in ['shared', 'both']`

2022-06-22 09:54 UTC, ArsenArsen approved these changes

2022-06-22 17:16 UTC, Geertiebear approved these changes
LGTM in general, one small comment though.

2022-06-22 17:16 UTC, Geertiebear commented on meson.build
> +			'-DFRIGG_HAVE_LIBC',
Is this define even still used? It seems weird to me that it's defined for the static case but not the dynamic case.

2022-06-24 07:26 UTC, merged