abis/linux: Add various missing ip related structs and defines
managarm/mlibc pull request #548
Opened 2022-06-25 13:05 UTC by Dennisbonke

Split off from #541 

Part of the mlibc LFS projec

2022-06-25 16:45 UTC, 64 requested changes

2022-06-25 16:45 UTC, 64 commented on abis/linux/in.h
> +extern const struct in6_addr in6addr_any;
We already define this in `options/posix/include/netinet/in.h`, so I think this should be removed.

2022-06-25 16:45 UTC, 64 commented on abis/linux/in.h
> +#define __UAPI_DEF_IN_ADDR      0
It might be nice to add a brief comment why these are needed.

2022-06-26 13:42 UTC, ArsenArsen reviewed
we should consider this practice in a wider sense across the tree

2022-06-26 13:42 UTC, ArsenArsen commented on abis/linux/in.h
> +#define __UAPI_DEF_IP6_MTUINFO  0
we should just use the kernel definitions instead (on linux at least)

2022-06-30 10:22 UTC, avdgrinten commented
Before we add any more `__UAPI` compatibility we should set up a policy to decide (i) what we take from UAPI and what we don't, (ii) what we do on non-Linux systems (seems a bit pointless to rely on the UAPI headers on the one hand, while also duplicating them for all other OSes?) and we should document that properly, see #582.

After this is properly decided and documented, we should go through the existing headers and clean them up.

2022-07-17 15:19 UTC, Dennisbonke commented
So what is the status on this one? I'm lost on what the actual consensus is now, can we merge this or is there anything I need to do?

2022-07-29 00:11 UTC, Dennisbonke commented
So, can we merge this one then?

2022-10-19 12:04 UTC, no92 approved these changes

2022-10-24 19:53 UTC, ArsenArsen approved these changes
I think this is OK, all things considered, right?

2022-10-24 23:55 UTC, qookei approved these changes
Seems good to me too

2022-10-25 01:21 UTC, merged