options/posix: Stub get and setdomainname
managarm/mlibc pull request #561
Opened 2022-06-25 13:07 UTC by Dennisbonke

2022-06-25 13:31 UTC, avdgrinten approved these changes

2022-06-25 16:41 UTC, 64 commented
These should probably live in `options/glibc` instead, right? But that'd probably require some other changes anyway, so maybe we should make an issue for that and leave it to a future PR.

2022-06-25 16:45 UTC, ArsenArsen requested changes
Correct, but it's silly to stub this.

```
       On most Linux architectures (including x86), there is no getdomainname() system call; instead, glibc implements getdomainname() as a  library  func‐
       tion that returns a copy of the domainname field returned from a call to uname(2).
```
... and `setdomainname` is a syscall.

2022-07-14 15:16 UTC, ArsenArsen requested changes
The combined implementation for these two functions and their Linux sysdeps is under 50LoC, boilerplate included

2022-07-14 15:16 UTC, ArsenArsen commented on options/posix/generic/unistd-stubs.cpp
> +<<<<<<< HEAD
Merge markers

2022-07-14 15:17 UTC, Dennisbonke commented
> 

Unfortunately we don't have domainname in the mlibc abi, so that is blocked on abi-break. I move to implement this at a later point, and merge the stubs instead for now/

2022-07-14 15:28 UTC, Dennisbonke commented
> Didn't we just merge an abi-break because a struct was incorrect on Linux?

Yes, so the Linux abi is fine, but the mlibc abi is not fine until abi-break is merged into master. I don't want to wait on that.

2022-07-14 15:34 UTC, ArsenArsen commented
The struct access would be inside sysdeps to accomodate systems that have a getdomainname syscall anyway, and hence does not rely on the mlibc ABI on Linux

2022-07-18 12:02 UTC, Geertiebear commented
I don't think an implementation of these is required to merge this PR, that can always be done in a future PR. But the merge marker needs to be removed for it to build of course.

2022-07-18 19:46 UTC, 64 approved these changes

2022-07-18 21:37 UTC, ArsenArsen requested changes

2022-07-18 21:37 UTC, ArsenArsen commented on options/posix/include/unistd.h
> +// Glibc extensions
line comment

2022-07-20 21:46 UTC, Geertiebear approved these changes
LGTM.

2022-07-20 21:46 UTC, merged