options/posix: implement pthread_mutexattr
managarm/mlibc pull request #603
Opened 2022-07-01 18:38 UTC by 64

Progress on #530.

2022-07-03 13:49 UTC, ArsenArsen requested changes

2022-07-03 13:49 UTC, ArsenArsen commented on options/posix/generic/pthread-stubs.cpp
> +	memset(attr, 0, sizeof *attr);
we use function style sizeof

2022-07-03 17:00 UTC, 64 commented on options/posix/generic/pthread-stubs.cpp
> +	memset(attr, 0, sizeof *attr);
not at all consistently :^)

2022-07-14 13:55 UTC, Geertiebear approved these changes
LGTM.

2022-07-14 13:55 UTC, Geertiebear commented
Does this complete the mutexattr_t struct?

2022-07-14 15:58 UTC, 64 commented
> Does this complete the mutexattr_t struct?

We have
```c
struct __mlibc_mutex {
	unsigned int __mlibc_state;
	unsigned int __mlibc_recursion;
	unsigned int __mlibc_flags;
};
typedef struct __mlibc_mutex pthread_mutex_t;

struct  __mlibc_mutexattr {
	int __mlibc_type;
	int __mlibc_robust;
	int __mlibc_protocol;
	int __mlibc_pshared;
	int __mlibc_prioceiling;
};
typedef struct __mlibc_mutexattr pthread_mutexattr_t;
```

I guess it's just a question of which fields we can compress into `__mlibc_flags` here (I think all of them except `prioceiling`?)

2022-07-14 15:59 UTC, 64 commented
Oh disregard, yes `mutexattr_t` should be complete now but `mutex_t` is not necessarily (as per the above).

2022-07-18 12:00 UTC, Geertiebear commented
Then let's add a required field for prioceiling too, to avoid an ABI break in the future.

2022-07-19 03:18 UTC, 64 commented
> Then let's add a required field for prioceiling too, to avoid an ABI break in the future.

Done. I've also made the getprioceiling / setprioceiling functions return EINVAL (matching musl) since we don't implement that behaviour and it appears to be a pretty heavyweight feature.

2022-07-20 21:41 UTC, Geertiebear approved these changes
LGTM now then.

2022-07-20 21:41 UTC, merged