Fixes and additions to `strftime`
managarm/mlibc pull request #611
Opened 2022-07-02 13:22 UTC by no92

2022-07-03 03:19 UTC, 64 requested changes

2022-07-03 03:19 UTC, 64 commented on options/ansi/generic/time-stubs.cpp
> +		case 'I': {
`tm_hour` can be 0, can't it? In which case our logic here (and in `%r`) is wrong, since it needs to be printed in the range `01-12`.

2022-07-03 03:19 UTC, 64 commented on options/ansi/generic/time-stubs.cpp
> +				tm->tm_min, tm->tm_sec, nl_langinfo((tm->tm_hour < 12) ? AM_STR : PM_STR));
Same comment re. `tm_hour`

2022-07-03 03:26 UTC, 64 commented on options/ansi/generic/time-stubs.cpp
>  			}
While you're at it, you might as well deduplicate this so that it does
```c
snprintf(..., nl_langinfo((hour < 12) ? AM_STR : PM_STR));
```

2022-07-03 03:27 UTC, 64 commented on options/ansi/generic/time-stubs.cpp
> +	return (p - dest);
We should add a test that the length is correct.

2022-07-03 16:02 UTC, 64 approved these changes

2022-07-03 17:30 UTC, Geertiebear requested changes

2022-07-03 17:30 UTC, Geertiebear commented on options/internal/generic/locale.cpp
> +		__builtin_unreachable();
A ``default`` case with a more descriptive error message is more appropriate.

2022-07-05 11:33 UTC, Dennisbonke approved these changes
LGTM apart from 2 small changes.

2022-07-05 11:57 UTC, Geertiebear approved these changes
LGTM.

2022-07-05 11:57 UTC, merged