options/bsd: Add fstab.h header
managarm/mlibc pull request #624
Opened 2022-07-05 14:59 UTC by Dennisbonke

Part of the mlibc LFS project.

2022-07-05 15:37 UTC, ArsenArsen requested changes
What programs include this header in order to not use getfsent and friends?

2022-07-05 15:37 UTC, ArsenArsen commented on options/bsd/include/fstab.h
> +#endif // _FSTAB_H
Don't add C++-style comments in public interfaces.

2022-07-05 16:07 UTC, Dennisbonke commented
> What programs include this header in order to not use getfsent and friends?

`libsanitizers` makes use of this header.

2022-07-05 16:38 UTC, ArsenArsen commented
Looks like it's only used to determine the size of this header (couldn't the gcc devs come up with a better way to enumerate the systems structs?)

2022-07-18 08:41 UTC, Geertiebear approved these changes
LGTM.

2022-07-18 08:47 UTC, merged