options/posix: Add mqueue header
managarm/mlibc pull request #626
Opened 2022-07-05 14:59 UTC by Dennisbonke

Part of the mlibc LFS project.

2022-07-05 15:33 UTC, ArsenArsen requested changes

2022-07-05 15:33 UTC, ArsenArsen commented on options/posix/include/mqueue.h
> +#endif // _MQUEUE_H
Don't add C++-style headers to public-facing interfaces.

2022-07-06 09:36 UTC, Dennisbonke commented on options/posix/include/mqueue.h
> +	long __pad[4];
Unfortunately I think you're right, linux has a bits/mqueue.h header which defines the struct. I'll move it over to abi-bits.

2022-07-21 17:06 UTC, Geertiebear approved these changes
Unfortunately this PR conflicts on latest master, rebase it and it's good to go.

2022-07-22 21:37 UTC, 64 requested changes

2022-07-22 21:37 UTC, 64 commented on sysdeps/linux/meson.build
> +		host_machine.cpu_family() / 'abi-bits/arch-syscall.h',
looks unrelated

2022-07-22 21:37 UTC, 64 commented on options/posix/include/mqueue.h
> +
why is there a newline :^)

2022-07-23 08:59 UTC, ArsenArsen commented on options/posix/include/mqueue.h
> +
in other places also

2022-07-23 08:59 UTC, ArsenArsen commented on sysdeps/linux/meson.build
> +		host_machine.cpu_family() / 'abi-bits/arch-syscall.h',
this was removed yes

2022-07-30 11:07 UTC, no92 approved these changes

2022-07-31 17:49 UTC, 64 approved these changes

2022-08-01 16:49 UTC, Geertiebear approved these changes

2022-08-01 16:49 UTC, merged