sysdeps/linux: Include unistd_64.h in syscall.h
managarm/mlibc pull request #641
Opened 2022-07-05 15:01 UTC by Dennisbonke

I got compilation failures if this header is not included, I'm unsure about whether this is correct, so feedback is appreciated.

Part of the mlibc LFS project.

2022-07-05 15:08 UTC, ArsenArsen commented
This is not correct.

2022-07-05 15:56 UTC, 64 commented
> This is not correct.

In what way?

2022-07-05 16:04 UTC, Dennisbonke commented
> We're supposed to include <asm/unistd.h>, which then includes unistd_64.h on x86_64, when `__X32__` isn't set, or something like that. I don't remember the details. This header also doesn't exist outside of x86_64 64bit.

Makes sense, I'll fix it.

2022-07-14 17:43 UTC, ArsenArsen requested changes

2022-07-14 17:43 UTC, ArsenArsen commented on sysdeps/linux/include/sys/syscall.h
> +#if __has_include("asm/unistd.h")
`__has_include(<asm/unistd.h>)`

2022-07-14 23:51 UTC, merged