options/rtdl: Ignore the first item in __dlapi_iterate_phdr
managarm/mlibc pull request #644
Opened 2022-07-05 15:02 UTC by Dennisbonke

This matches the behavior of glibc and pleases ASan.

co-authored-by: Matt Taylor <mstaveleytaylor@gmail.com>

2022-07-05 15:52 UTC, 64 commented
The arguments to `strstr` in `tests/rtdl/dl_iterate_phdr/test.c` need to be swapped for the test to pass.

2022-07-05 15:58 UTC, Dennisbonke commented
> The arguments to `strstr` in `tests/rtdl/dl_iterate_phdr/test.c` need to be swapped for the test to pass.

Noted, will fix soon.

2022-07-05 16:53 UTC, avdgrinten commented
I don't understand what this commit does.

2022-07-05 17:22 UTC, avdgrinten commented
Why do we check for the first object instead of checking for the executable?

2022-07-05 17:24 UTC, 64 commented
> Why do we check for the first object instead of checking for the executable?

They ought to be the same thing, but it's true that would be a better implementation.

2022-07-14 16:03 UTC, 64 requested changes

2022-07-14 16:03 UTC, 64 commented on options/rtdl/generic/main.cpp
> +		if(amount == 0) {
Instead of this `amount` variable, we should check `object->isMainObject`

2022-07-14 16:04 UTC, 64 commented
Also merge conflict

2022-07-14 17:48 UTC, 64 approved these changes

2022-07-18 11:55 UTC, Geertiebear approved these changes
LGTM.

2022-07-18 11:56 UTC, Geertiebear requested changes
Actually, do we test for this behaviour, and if not, can that be added?

2022-07-18 16:13 UTC, 64 commented
Yeah actually, there's some commented out lines we can re-enable in the test.

2022-07-18 19:52 UTC, 64 approved these changes

2022-07-20 21:19 UTC, Geertiebear approved these changes

2022-07-20 21:19 UTC, merged