Various fixes for LFS, number 2
managarm/mlibc pull request #651
Opened 2022-07-08 00:37 UTC by no92

2022-07-08 01:10 UTC, 64 requested changes

2022-07-08 01:10 UTC, 64 commented on options/ansi/include/string.h
> +	return _gnu_basename_c(const_cast<char *>(path));
Unnecessary `const_cast`

2022-07-08 01:10 UTC, 64 commented on tests/glibc/gnu-basename.c
> +	/* intentionally a macro */
```suggestion
	/* intentionally a macro: basename modifies its argument */
```

2022-07-08 14:25 UTC, ArsenArsen commented on options/ansi/include/string.h
> + * implementation, otherwise, we use the GNU one. since our ABI previously
nah that's boring

2022-07-08 14:26 UTC, ArsenArsen commented on options/glibc/generic/string.cpp
> + */
what?

2022-07-08 14:28 UTC, ArsenArsen commented on options/ansi/include/string.h
> +#define basename _gnu_basename
we can't, since libgen.h is supposed to override it if included later (read the supposedly superfluous comment explaining what's going on here)

2022-07-08 14:49 UTC, 64 commented on options/ansi/include/string.h
> +#define basename _gnu_basename
Ah, the ABI break is annoying indeed (we can fix that on abi-break). Are the C++ overloads necessary? We don't do them for other functions.

2022-07-08 15:10 UTC, ArsenArsen commented on options/ansi/include/string.h
> +#define basename _gnu_basename
yeah, to propagate constness of the input argument (which matters to C++ programs)

also, this isn't an abi break, we just can't redeclare basename under a different name (think of a scenario when you include <string.h> then <libgen.h>, if this was a concrete symbol called basename, libgen.h wouldn't be able to override it)

what distinguishes this from (AFAIK) every other function in libc is that XPG and GNU in parallel defined them to mean different things, and programs are using both, which means we have to provide both.

XPG defines basename in the way that we already did (and our implementation is correct, and I didn't remove it to add the GNU one), and GNU defines strrchr('/')+1 essentially (which is also pretty handy), and specifies how one is picked over the other.

2022-07-08 15:10 UTC, avdgrinten commented
PR should be narrow in scope and have reasonable summaries. "Various fixes" is not reasonable.

2022-07-08 15:18 UTC, 64 commented on options/ansi/include/string.h
> +#define basename _gnu_basename
> I don't think that there is an ABI break.

Yes, I'm saying that we should add a commit on abi-break to get rid of the `#define` / `#undef` dance that we do here (we'd only need a `#define` inside `libgen.h` afaics)

2022-07-08 15:18 UTC, 64 commented on options/ansi/include/string.h
> +#define basename _gnu_basename
> yeah, to propagate constness of the input argument (which matters to C++ programs)

But we don't do them for other functions, do we?

2022-07-08 15:20 UTC, ArsenArsen commented on options/ansi/include/string.h
> +#define basename _gnu_basename
> Yes, I'm saying that we should add a commit on abi-break to get rid of the `#define` / `#undef` dance that we do here (we'd only need a `#define` inside `libgen.h` afaics)

what? how would this be preventable at all? we still need two symbols and we still need a define to decide which to use at runtime



> > yeah, to propagate constness of the input argument (which matters to C++ programs)
> 
> But we don't do them for other functions, do we?

other functions aren't expected to do this (glibc does this explicitly)

2022-07-08 15:24 UTC, 64 commented on options/ansi/include/string.h
> +#define basename _gnu_basename
I don't follow. `strstr` also takes `const char *` and returns `char *`, as does `gnu_basename_c`. How is this a different scenario?

2022-07-08 15:27 UTC, ArsenArsen commented on options/ansi/include/string.h
> +#define basename _gnu_basename
Becuase strstr isn't expected to do this overload, and glibc explicitly does this overload (so it's expected that this extra bit of strictness exists)

2022-07-08 16:09 UTC, no92 commented
Narrowed down the PR to only include fixes from LFS.

2022-07-08 16:36 UTC, 64 approved these changes

2022-07-10 15:34 UTC, ArsenArsen approved these changes

2022-07-10 16:07 UTC, Geertiebear approved these changes
LGTM.

2022-07-10 16:07 UTC, merged