Additions and fixes for LFS, part 3
managarm/mlibc pull request #655
Opened 2022-07-08 18:12 UTC by no92

2022-07-08 20:05 UTC, 64 approved these changes

2022-07-08 20:31 UTC, avdgrinten commented on options/posix/generic/posix_stdlib.cpp
> +		}
I don't think that this is correct. This is supposed to handle `/` inputs, right? However, `//` is equivalent to `/` and that is not handled.

2022-07-09 09:56 UTC, Dennisbonke requested changes
Looks good, a few minor nitpicks.

2022-07-09 09:56 UTC, Dennisbonke commented on options/glibc/include/sys/ioctl.h
> +#define SIOCPROTOPRIVATE 0x89E0
We sort these by value from what I can tell. Swap this one around with the other one to match that.

2022-07-09 09:56 UTC, Dennisbonke commented on options/linux/generic/sys-klog.cpp
> +#include "mlibc/linux-sysdeps.hpp"
Why the use of `”` here? We should be able to use `<>` here if I’m not mistaken.

2022-07-09 09:56 UTC, Dennisbonke commented on options/linux/include/sys/klog.h
> +#endif // _SYS_KLOG_H
We shouldn’t use C++ style comments in public headers.

2022-07-09 13:17 UTC, ArsenArsen requested changes

2022-07-09 13:17 UTC, ArsenArsen commented on options/linux/generic/sys-klog.cpp
> +	if (int e = mlibc::sys_syslog(type, bufp, len, &out); e) {
The name of this syscall is an unfortunate thing on Linux. We shouldn't preserve that, and we should just call this sys_klogctl instead.

2022-07-23 20:48 UTC, 64 approved these changes

2022-07-24 07:56 UTC, ArsenArsen approved these changes

2022-07-24 11:00 UTC, no92 commented
Squashed the fixups.

2022-08-01 16:48 UTC, Geertiebear approved these changes

2022-08-01 16:48 UTC, merged