options/glibc: Add iopl, ioperm and the port i/o functions
managarm/mlibc pull request #688
Opened 2022-07-20 20:23 UTC by Dennisbonke

More Valgrind additions.

Part of the mlibc LFS project.

2022-07-20 21:01 UTC, ArsenArsen requested changes
is this header x86(_64) only? I'm unsure

2022-07-20 21:01 UTC, ArsenArsen commented on options/glibc/generic/sys-io.cpp
> +}
both of these are x86(_64) specific and syscall wrappers, stubbing them is extremely silly

2022-07-20 21:04 UTC, 64 commented on options/glibc/include/sys/io.h
> +static __inline unsigned char inb(unsigned short int port) {
(= `__MLIBC_INLINE_DEFINITION`)

2023-04-06 13:11 UTC, no92 commented
Rebased onto current master and addressed the comments raised about the header.

2023-08-10 21:24 UTC, no92 commented
Implemented `ioperm` and `iopl` with sysdeps for Linux, also rebased on master.

2023-08-10 21:27 UTC, Geertiebear approved these changes
LGTM

2023-08-10 22:11 UTC, merged