options/posix: Make sendto and recvfrom use a sysdep on linux
managarm/mlibc pull request #694
Opened 2022-07-20 20:23 UTC by Dennisbonke

Linux has an actual sysdep for `sendto` and `recvfrom`. Use that instead of passing it through to `sendmsg` and `recvmsg`.

Part of the mlibc LFS project.

2022-07-20 20:58 UTC, ArsenArsen requested changes
why are we doing this? sendto is a strict superset of sendmsg; ditto for recvmsg; also, `__linux__` is certainly not the way to test for this. if we're providing subset/superset sysdeps and fallthroughs, we need a concise and coherent system (for instance, picking out the first found sysdep, which could be done by a macro that takes varargs and searches for it, then returns it, or something)

2022-07-20 20:59 UTC, Dennisbonke commented
> why are we doing this? sendto is a strict superset of sendmsg; ditto for recvmsg; also, `__linux__` is certainly not the way to test for this. if we're providing subset/superset sysdeps and fallthroughs, we need a concise and coherent system (for instance, picking out the first found sysdep, which could be done by a macro that takes varargs and searches for it, then returns it, or something)

Well I was trying just about everything to fix some bugs, it could well be that this change is indeed unneeded. Afaik nothing hard depends on it so we can drop it if that is preferred.

2022-07-20 21:08 UTC, 64 requested changes

2022-07-20 21:08 UTC, 64 commented on sysdeps/linux/generic/sysdeps.cpp
> +        if (int e = sc_error(ret); e)
indentation is wrong

2022-07-20 21:08 UTC, 64 commented on options/posix/generic/sys-socket-stubs.cpp
> +#ifndef __linux__
I agree that it'd be better to use sendmsg as a fallback instead of this define

2022-07-20 21:12 UTC, ArsenArsen commented
what bug was that? and we don't have an established precedent here, so if we're going down the route of having redundant sysdeps, we should figure out how

2022-07-20 21:13 UTC, Dennisbonke commented
> what bug was that? and we don't have an established precedent here, so if we're going down the route of having redundant sysdeps, we should figure out how

Weston hanging, which we for now presumably traced to a pthread issue. I'm more than fine with dropping this change because of that.

2022-07-22 12:42 UTC, Geertiebear commented
We've always favoured supersets of sysdeps over redundant ones, and since there was no bug fixed by this change I will close this. Of course if there is a bug involved with these sysdeps, we can reconsider these changes.

2022-07-22 12:42 UTC, closed without merging