options/glibc: simplify basename ABI and implementation
managarm/mlibc pull request #721
Opened 2022-08-05 18:36 UTC by 64

This will need to be backported to the release branch.

2022-08-05 18:44 UTC, 64 commented
ABI check fails, but that's deliberate.

2022-08-12 19:59 UTC, ArsenArsen requested changes
I wouldn't mind removing the overloads if we decide to do that to be consistent with other string functions (though, it can change semantics of c++ programs, which is something to consider before finalizing a decision), but swapping the `__mlibc_gnu_basename_c` and `basename` symbols is a very unnecessary ABI break

2022-08-12 19:59 UTC, ArsenArsen commented on options/posix/include/libgen.h
> +#define basename __mlibc_xpg_basename
this will generate a redefinition warning

2022-08-12 19:59 UTC, ArsenArsen commented on options/posix/generic/libgen-stubs.cpp
> +// Note that 'basename' here is defined to be __mlibc_xpg_basename by libgen.h.
I'm not sure this is sane

2022-08-12 19:59 UTC, ArsenArsen commented on options/ansi/include/string.h
> +char *basename(const char *path);
again, this was deliberate (it prevents the `char * x = basename((const char *)"abc");` case.

2022-08-12 20:11 UTC, closed without merging