utmp implementations from LFS
managarm/mlibc pull request #734
Opened 2022-09-06 18:27 UTC by no92

2022-10-11 15:02 UTC, Geertiebear requested changes
Unfortunately we can't include GPL'd code in mlibc.

2022-10-11 15:02 UTC, Geertiebear commented on options/linux/generic/utmp-stubs.cpp
> + * The code in this file is largely based on glibc.
This is a license conflict.

2023-04-06 12:01 UTC, no92 commented on options/linux/generic/utmp-stubs.cpp
> + * The code in this file is largely based on glibc.
The offending commits were dropped.

2023-04-06 12:05 UTC, no92 commented
Dropped the offending commits and rebased onto master.

2023-04-08 11:12 UTC, Dennisbonke approved these changes
I believe that this is good to go now, not as extensive as it once was, but progress none the less and no more license violations! LGTM.

2023-04-08 13:43 UTC, merged