Various function implementations from LFS
managarm/mlibc pull request #735
Opened 2022-09-06 18:55 UTC by no92

2022-09-06 18:59 UTC, no92 commented
The ABI checker complaining is intended and should not result in an ABI break.

2022-10-11 15:09 UTC, Geertiebear commented on options/linux/include/sys/swap.h
> +#define	SWAP_FLAG_PREFER		0x8000
What happened to the formatting here?

2022-10-17 17:42 UTC, avdgrinten commented on options/glibc/include/sys/user.h
> +#include <mlibc/arch-defs.h>
`mlibc/` headers must not be included from public headers. Use `bits/` instead.

2023-04-05 23:24 UTC, Dennisbonke requested changes
LGTM, one comment.

2023-04-05 23:24 UTC, Dennisbonke commented on options/linux/include/sys/swap.h
> +#endif // _SYS_SWAP_H
We should use C style comments here.

2023-04-06 00:14 UTC, Dennisbonke approved these changes
LGTM

2023-04-06 00:18 UTC, merged