glibc: implement getopt_long_only
managarm/mlibc pull request #741
Opened 2022-09-13 19:18 UTC by no92

2023-01-28 23:37 UTC, no92 commented
Ready for review now.

2023-02-04 19:11 UTC, 64 requested changes

2023-02-04 19:11 UTC, 64 commented on options/glibc/generic/getopt-stubs.cpp
> +extern int optreset __attribute__((weak, alias("__optreset")));
ifdef this behind BSD option?

2023-02-04 19:11 UTC, 64 commented on tests/glibc/getopt.c
> +	int test_argc = 7;
6?

2023-02-04 21:17 UTC, 64 approved these changes

2023-02-04 21:17 UTC, 64 commented on options/glibc/generic/getopt-stubs.cpp
> +enum GetoptMode {
enum class?

2023-02-04 23:08 UTC, Dennisbonke approved these changes
LGTM

2023-02-06 08:34 UTC, merged