Remove the `linux-headers` option, instead allow for supplying original headers
managarm/mlibc pull request #784
Opened 2023-01-29 23:08 UTC by no92

The second commit makes this an ABI-break, though.

2023-01-30 09:54 UTC, ArsenArsen commented
ISTR that struct ifreq stuff elsewhere, and some discussion about whether it's even an ABI break.  Could you check other PRs for it?

2023-01-30 21:47 UTC, no92 commented
Added a section in the README explaining how the `linux_kernel_headers` meson option works.

2023-02-04 21:45 UTC, Dennisbonke requested changes
LGTM but one change

2023-02-04 21:45 UTC, Dennisbonke commented on .github/workflows/ci.yml
> +                    "-Db_sanitize=undefined" \
This is double.

2023-02-04 21:54 UTC, 64 approved these changes

2023-02-04 21:54 UTC, 64 commented on .github/workflows/ci.yml
> +                    "-Db_sanitize=undefined" \
duplicate line?

2023-02-05 00:09 UTC, Dennisbonke approved these changes
LGTM

2023-02-05 00:12 UTC, merged