LFS: minor fixes 2
managarm/mlibc pull request #815
Opened 2023-03-28 23:36 UTC by no92

2023-03-28 23:43 UTC, Dennisbonke requested changes
3 style issues, other than that, LGTM.

2023-03-28 23:43 UTC, Dennisbonke commented on options/posix/generic/arpa-inet-stubs.cpp
> +					if(off < size) dst[off++] = ':';
Style issue, this should be
```c
if(off < size) {
	dst[off++] = ':';
}
```

2023-03-28 23:43 UTC, Dennisbonke commented on options/posix/generic/arpa-inet-stubs.cpp
> +					if(off < size) dst[off++] = ':';
Same as above.

2023-03-28 23:43 UTC, Dennisbonke commented on options/posix/generic/arpa-inet-stubs.cpp
> +					if(off < size) dst[off++] = ':';
Same as above.

2023-03-29 00:00 UTC, Andy-Python-Programmer approved these changes
Andy approved :)

2023-03-29 00:01 UTC, Dennisbonke approved these changes
LGTM

2023-03-29 00:05 UTC, merged