LFS: part 10, sysdeps
managarm/mlibc pull request #833
Opened 2023-04-06 21:56 UTC by no92

2023-04-06 22:21 UTC, ikbenlike reviewed
from `recvfrom(2)`:
> The recv() call is normally used only on a connected socket (see connect(2) and is identical to recvfrom() with a NULL src_addr argument.

I am unsure if mlibc already provides `recv`, however it might be worth it to simplify the implementation of it like this (and if not yet provided, it would be relatively simple to do so)

2023-04-06 22:21 UTC, ikbenlike commented on options/posix/generic/sys-socket-stubs.cpp
> +#ifndef __linux__
should this not take place in the implementation of the sysdep?

2023-04-06 22:21 UTC, ikbenlike commented on options/posix/generic/sys-socket-stubs.cpp
> +#ifndef __linux__
same as with `recvfrom`

2023-04-06 23:25 UTC, ikbenlike commented
I just checked and `recv` is already implemented as a call to `recvfrom`, and the fallback in case there is no sysdep is now handled more elegantly. personally I can't think of anything else that should be changed in this PR

2023-04-08 11:29 UTC, Dennisbonke approved these changes
LGTM

2023-04-08 12:15 UTC, Geertiebear requested changes

2023-04-08 12:15 UTC, Geertiebear commented on options/posix/include/mlibc/posix-sysdeps.hpp
> +[[gnu::weak]] int sys_accept(int fd, int *newfd, struct sockaddr *addr_ptr, socklen_t *addr_length, int flags);
The change of this sysdep should be propagated to other ports as well. Also make sure that the functionality stays the same (so copy the old ``fcntl()`` trick to the sysdeps as well).

2023-04-10 16:50 UTC, Geertiebear approved these changes
LGTM now.

2023-04-10 16:50 UTC, merged