misc: Remove root /abis directory and move headers to /sysdeps
managarm/mlibc pull request #852
Opened 2023-04-11 13:19 UTC by mintsuki

Get rid of the root `/abis` directory and move all the ABI headers to `/sysdeps`.

As discussed in the Discord, the `/abis` directory is mostly redundant and the separation is not useful.

2023-04-16 17:22 UTC, qookei requested changes

2023-04-16 17:22 UTC, qookei commented on sysdeps/dripos/include/abi-bits/signal.h
`managarm/include/abi-bits/signal.h` is a symlink to the Linux `signal.h`, not a copy of the mlibc ABI `signal.h`

2023-04-16 17:22 UTC, qookei commented on sysdeps/dripos/include/abi-bits/termios.h
`managarm/include/abi-bits/termios.h` is a symlink to the Linux `termios.h`, not the mlibc ABI `termios.h`

2023-04-16 17:22 UTC, qookei commented on sysdeps/dripos/include/abi-bits/wait.h
`managarm/include/abi-bits/wait.h` is a symlink to the Linux `wait.h`, not the mlibc ABI `wait.h`

2023-04-17 06:03 UTC, mintsuki commented
@qookei I have moved the mlibc ABI to `/sysdeps/legacy-mlibc-abi` as a compromise, whilst the rest is the same as it was before this force push, save for stuff that you mentioned that should've been fixed.

2023-04-17 08:08 UTC, Dennisbonke commented
> I've already voiced concern over this approach on Discord, but will do it here as well for clarity's sake: I don't like the relative symlinking happening inside the sysdep directory to pick ABI's. This is very fragile, and will mean ABI (or now also sysdep) changes will be cumbersome to propagate. 

I second this opinion. For me, it feels wrong to symlink to other sysdeps.

2023-04-17 08:18 UTC, mintsuki commented
Since we're just reposting what was said on the Discord now, I will restate how "feels wrong" isn't a technical reason to do or not do something technical.

2023-04-17 17:47 UTC, Geertiebear commented
"Feels wrong" in this case has been supported by an actual argument, giving rise to this "wrong" feeling.

2023-04-22 09:45 UTC, closed without merging