Add hdoc support
managarm/mlibc pull request #887
Opened 2023-08-02 23:19 UTC by no92

Counterpart to managarm/bootstrap-managarm#255.

2023-08-03 01:16 UTC, ArsenArsen requested changes
please add build system integration (including generating this file)

2023-08-03 01:16 UTC, ArsenArsen commented on .hdoc.toml
> +compile_commands = "../../build/pkg-builds/mlibc/compile_commands.json"
?

2023-08-03 20:08 UTC, ElectrodeYT approved these changes
LGTM

2023-08-05 10:28 UTC, ArsenArsen requested changes
no need for messy hacks.. just configure the file and add a target that runs hdoc

2023-08-05 10:28 UTC, ArsenArsen commented on scripts/hdoc-config.sh
> +echo "compile_commands = \"$2/compile_commands.json\"" >> "$1"
https://mesonbuild.com/Reference-manual_functions.html#configure_file

2023-08-07 21:11 UTC, ArsenArsen commented on meson.build
> +			'exec ' + hdoc.full_path() + ' --verbose'
why?

2023-08-08 18:37 UTC, ArsenArsen approved these changes
pre-configuration files are usually suffixed .in, other than that, lgtm

2023-08-10 14:24 UTC, Geertiebear reviewed
Yeah, if the ``.template`` could be changed to ``.in`` then this is fine by me. Thanks for adding this, should provide a nice way to start writing some detailed docs for mlibc!

2023-08-10 19:55 UTC, no92 commented
Renamed the file to use the `.in` suffix.

2023-08-10 20:55 UTC, merged