options/glibc: Add utmpx paths
managarm/mlibc pull request #913
Opened 2023-08-25 13:17 UTC by Dennisbonke

options/linux: Define more utmpx stuff

2023-08-28 23:13 UTC, no92 approved these changes
LGTM

2023-08-29 08:35 UTC, Geertiebear requested changes

2023-08-29 08:35 UTC, Geertiebear commented on options/linux/generic/utmpx.cpp
> +	// return NULL as musl does
Maybe add an info log here that we haven't implemented this, as it is a genuinly useful interface.

2024-02-29 21:45 UTC, Geertiebear approved these changes

2024-02-29 21:45 UTC, merged